### ISSUE TITLE
In /addresses api, '+' is not working in sort query params.

### ISSUE THREAD

**Issue by athoifss** [sudoblockio/icon-go-api#20]
- https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=25&skip=0.
  This works fine

- https://tracker.icon.community/api/v1/addresses?sort=+balance&limit=25&skip=0.
  This returns invalid sort parameter. 
   '%2Bbalance% works instead of '+balance' 
   https://tracker.icon.community/api/v1/addresses?sort=%2Bbalance&limit=25&skip=0

**Comment by robcxyz** [comment]
Works from swagger to local but not from chrome + postman. + is replaced with " ". 

Easy way to side step this is to make the `-` the same as the `+` now and not have anything for the `+`. 

So this would be it 

https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=25&skip=0.
https://tracker.icon.community/api/v1/addresses?sort=balance&limit=25&skip=0.

Basically opposite than it is now with no `+`

**Comment by robcxyz** [comment]
Works from swagger to local but not from chrome + postman. + is replaced with " ". 

Easy way to side step this is to make the `-` the same as the `+` now and not have anything for the `+`. 

So this would be it 

https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=25&skip=0.
https://tracker.icon.community/api/v1/addresses?sort=balance&limit=25&skip=0.

Basically opposite than it is now with no `+`

**Comment by robcxyz** [comment]
Works from swagger to local but not from chrome + postman. + is replaced with " ". 

Easy way to side step this is to make the `-` the same as the `+` now and not have anything for the `+`. 

So this would be it 

https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=25&skip=0.
https://tracker.icon.community/api/v1/addresses?sort=balance&limit=25&skip=0.

Basically opposite than it is now with no `+`
