### ISSUE TITLE
in /addresses api, negative sort (sort = -paramName) does not return the right data

### ISSUE THREAD

**Issue by athoifss** [sudoblockio/icon-go-api#27]
- For example both these return data with transaction_count = 0
https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=100&skip=5000
https://tracker.icon.community/api/v1/addresses?sort=-transaction_count&limit=25&skip=150000

**Comment by robcxyz** [comment]
Not sure I follow. For these examples I would RM the large `&skip=5000`

https://tracker.icon.community/api/v1/addresses?sort=-balance&limit=100
- This is sorted by balance descending - not related to tx count 
https://tracker.icon.community/api/v1/addresses?sort=-transaction_count&limit=25
- This is sorted by tx count but descending so this is right that these have no Tx count 
- For tx count, rm the `-` in front of query param 
  - https://tracker.icon.community/api/v1/addresses?sort=transaction_count&limit=25
